export const statColor: Record<string, string> = {
  hp: "bg-red-500",
  attack: "bg-orange-500",
  defense: "bg-yellow-500",
  "special-attack": "bg-blue-500",
  "special-defense": "bg-green-500",
  speed: "bg-pink-500",
};

export const statDisplayName: Record<string, string> = {
    hp: "HP",
    attack: "Ataque",
    defense: "Defensa",
    "special-attack": "Ataque Especial",
    "special-defense": "Defensa Especial",
    speed: "Velocidad",
};

export const typeColors: Record<string, string> = {
  normal: "bg-gray-300 text-gray-800 dark:bg-gray-700 dark:text-gray-100",
  fire: "bg-red-400 text-white dark:bg-red-700 dark:text-white",
  water: "bg-blue-400 text-white dark:bg-blue-700 dark:text-white",
  grass: "bg-green-400 text-white dark:bg-green-700 dark:text-white",
  electric: "bg-yellow-300 text-yellow-900 dark:bg-yellow-500 dark:text-yellow-900",
  ice: "bg-cyan-200 text-cyan-900 dark:bg-cyan-500 dark:text-cyan-900",
  fighting: "bg-orange-500 text-white dark:bg-orange-700 dark:text-white",
  poison: "bg-purple-400 text-white dark:bg-purple-700 dark:text-white",
  ground: "bg-yellow-700 text-white dark:bg-yellow-900 dark:text-white",
  flying: "bg-indigo-200 text-indigo-900 dark:bg-indigo-500 dark:text-indigo-100",
  psychic: "bg-pink-400 text-white dark:bg-pink-700 dark:text-white",
  bug: "bg-lime-400 text-lime-900 dark:bg-lime-700 dark:text-lime-100",
  rock: "bg-yellow-800 text-white dark:bg-yellow-900 dark:text-white",
  ghost: "bg-violet-700 text-white dark:bg-violet-900 dark:text-white",
  dragon: "bg-indigo-600 text-white dark:bg-indigo-900 dark:text-white",
  dark: "bg-gray-800 text-white dark:bg-gray-900 dark:text-white",
  steel: "bg-gray-400 text-gray-900 dark:bg-gray-600 dark:text-gray-100",
  fairy: "bg-pink-200 text-pink-900 dark:bg-pink-400 dark:text-pink-900",
  fuego: "bg-red-400 text-white dark:bg-red-700 dark:text-white",
  agua: "bg-blue-400 text-white dark:bg-blue-700 dark:text-white",
  planta: "bg-green-400 text-white dark:bg-green-700 dark:text-white",
  eléctrico: "bg-yellow-300 text-yellow-900 dark:bg-yellow-500 dark:text-yellow-900",
  hielo: "bg-cyan-200 text-cyan-900 dark:bg-cyan-500 dark:text-cyan-900",
  lucha: "bg-orange-500 text-white dark:bg-orange-700 dark:text-white",
  veneno: "bg-purple-400 text-white dark:bg-purple-700 dark:text-white",
  tierra: "bg-yellow-700 text-white dark:bg-yellow-900 dark:text-white",
  volador: "bg-indigo-200 text-indigo-900 dark:bg-indigo-500 dark:text-indigo-100",
  psíquico: "bg-pink-400 text-white dark:bg-pink-700 dark:text-white",
  bicho: "bg-lime-400 text-lime-900 dark:bg-lime-700 dark:text-lime-100",
  roca: "bg-yellow-800 text-white dark:bg-yellow-900 dark:text-white",
  fantasma: "bg-violet-700 text-white dark:bg-violet-900 dark:text-white",
  dragón: "bg-indigo-600 text-white dark:bg-indigo-900 dark:text-white",
  siniestro: "bg-gray-800 text-white dark:bg-gray-900 dark:text-white",
  acero: "bg-gray-400 text-gray-900 dark:bg-gray-600 dark:text-gray-100",
  hada: "bg-pink-200 text-pink-900 dark:bg-pink-400 dark:text-pink-900",
};
