import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Navbar from "./_components/Navbar";
import { LanguageProvider } from "@/context/LanguageContext";
import { LoadingProvider } from "@/context/LoadingContext";
import { ClientThemeProvider } from "./_components/ClientThemeProvider";

export const metadata: Metadata = {
  title: "PokeAPI App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} h-full`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground h-full">
        <ClientThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <TRPCReactProvider>
            <LanguageProvider>
              <LoadingProvider>
                <div className="flex h-full flex-col">
                  <Navbar />
                  <main id="main-scroll" className="flex-grow overflow-y-auto">
                    {children}
                  </main>
                </div>
              </LoadingProvider>
            </LanguageProvider>
          </TRPCReactProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
